//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebATP.AisDataWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipVoyageData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ShipVoyageData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MMSIField;
        
        private int NavstatusField;
        
        private double SOGField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private double COGField;
        
        private int headingField;
        
        private int TimeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mess_timeField;
        
        private int AlarmeOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        private int IMO_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Call_signField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private double lengthField;
        
        private double widthField;
        
        private double draughtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ETAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MMSI {
            get {
                return this.MMSIField;
            }
            set {
                if ((this.MMSIField.Equals(value) != true)) {
                    this.MMSIField = value;
                    this.RaisePropertyChanged("MMSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Navstatus {
            get {
                return this.NavstatusField;
            }
            set {
                if ((this.NavstatusField.Equals(value) != true)) {
                    this.NavstatusField = value;
                    this.RaisePropertyChanged("Navstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double SOG {
            get {
                return this.SOGField;
            }
            set {
                if ((this.SOGField.Equals(value) != true)) {
                    this.SOGField = value;
                    this.RaisePropertyChanged("SOG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double COG {
            get {
                return this.COGField;
            }
            set {
                if ((this.COGField.Equals(value) != true)) {
                    this.COGField = value;
                    this.RaisePropertyChanged("COG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int heading {
            get {
                return this.headingField;
            }
            set {
                if ((this.headingField.Equals(value) != true)) {
                    this.headingField = value;
                    this.RaisePropertyChanged("heading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int TimeDate {
            get {
                return this.TimeDateField;
            }
            set {
                if ((this.TimeDateField.Equals(value) != true)) {
                    this.TimeDateField = value;
                    this.RaisePropertyChanged("TimeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Mess_time {
            get {
                return this.Mess_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.Mess_timeField, value) != true)) {
                    this.Mess_timeField = value;
                    this.RaisePropertyChanged("Mess_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int AlarmeOn {
            get {
                return this.AlarmeOnField;
            }
            set {
                if ((this.AlarmeOnField.Equals(value) != true)) {
                    this.AlarmeOnField = value;
                    this.RaisePropertyChanged("AlarmeOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int IMO_number {
            get {
                return this.IMO_numberField;
            }
            set {
                if ((this.IMO_numberField.Equals(value) != true)) {
                    this.IMO_numberField = value;
                    this.RaisePropertyChanged("IMO_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Call_sign {
            get {
                return this.Call_signField;
            }
            set {
                if ((object.ReferenceEquals(this.Call_signField, value) != true)) {
                    this.Call_signField = value;
                    this.RaisePropertyChanged("Call_sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public double length {
            get {
                return this.lengthField;
            }
            set {
                if ((this.lengthField.Equals(value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public double width {
            get {
                return this.widthField;
            }
            set {
                if ((this.widthField.Equals(value) != true)) {
                    this.widthField = value;
                    this.RaisePropertyChanged("width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public double draught {
            get {
                return this.draughtField;
            }
            set {
                if ((this.draughtField.Equals(value) != true)) {
                    this.draughtField = value;
                    this.RaisePropertyChanged("draught");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ETA {
            get {
                return this.ETAField;
            }
            set {
                if ((object.ReferenceEquals(this.ETAField, value) != true)) {
                    this.ETAField = value;
                    this.RaisePropertyChanged("ETA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AisDataWebservice.AISDataretrieverSoap")]
    public interface AISDataretrieverSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebATP.AisDataWebservice.HelloWorldResponse HelloWorld(WebATP.AisDataWebservice.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebATP.AisDataWebservice.HelloWorldResponse> HelloWorldAsync(WebATP.AisDataWebservice.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferAISPosition", ReplyAction="*")]
        void TransferAISPosition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferAISPosition", ReplyAction="*")]
        System.Threading.Tasks.Task TransferAISPositionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferShipVoyageData", ReplyAction="*")]
        void TransferShipVoyageData(int MMSI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferShipVoyageData", ReplyAction="*")]
        System.Threading.Tasks.Task TransferShipVoyageDataAsync(int MMSI);
        
        // CODEGEN: Generating message contract since element name TransferShipVoyageDataToServerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferShipVoyageDataToServer", ReplyAction="*")]
        WebATP.AisDataWebservice.TransferShipVoyageDataToServerResponse TransferShipVoyageDataToServer(WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferShipVoyageDataToServer", ReplyAction="*")]
        System.Threading.Tasks.Task<WebATP.AisDataWebservice.TransferShipVoyageDataToServerResponse> TransferShipVoyageDataToServerAsync(WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferShipHistory", ReplyAction="*")]
        void TransferShipHistory(int MMSI, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferShipHistory", ReplyAction="*")]
        System.Threading.Tasks.Task TransferShipHistoryAsync(int MMSI, System.DateTime startTime, System.DateTime endTime);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebATP.AisDataWebservice.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebATP.AisDataWebservice.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebATP.AisDataWebservice.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebATP.AisDataWebservice.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferShipVoyageDataToServerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransferShipVoyageDataToServer", Namespace="http://tempuri.org/", Order=0)]
        public WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequestBody Body;
        
        public TransferShipVoyageDataToServerRequest() {
        }
        
        public TransferShipVoyageDataToServerRequest(WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferShipVoyageDataToServerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MMSI;
        
        public TransferShipVoyageDataToServerRequestBody() {
        }
        
        public TransferShipVoyageDataToServerRequestBody(int MMSI) {
            this.MMSI = MMSI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferShipVoyageDataToServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransferShipVoyageDataToServerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebATP.AisDataWebservice.TransferShipVoyageDataToServerResponseBody Body;
        
        public TransferShipVoyageDataToServerResponse() {
        }
        
        public TransferShipVoyageDataToServerResponse(WebATP.AisDataWebservice.TransferShipVoyageDataToServerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferShipVoyageDataToServerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebATP.AisDataWebservice.ShipVoyageData TransferShipVoyageDataToServerResult;
        
        public TransferShipVoyageDataToServerResponseBody() {
        }
        
        public TransferShipVoyageDataToServerResponseBody(WebATP.AisDataWebservice.ShipVoyageData TransferShipVoyageDataToServerResult) {
            this.TransferShipVoyageDataToServerResult = TransferShipVoyageDataToServerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AISDataretrieverSoapChannel : WebATP.AisDataWebservice.AISDataretrieverSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AISDataretrieverSoapClient : System.ServiceModel.ClientBase<WebATP.AisDataWebservice.AISDataretrieverSoap>, WebATP.AisDataWebservice.AISDataretrieverSoap {
        
        public AISDataretrieverSoapClient() {
        }
        
        public AISDataretrieverSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AISDataretrieverSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AISDataretrieverSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AISDataretrieverSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebATP.AisDataWebservice.HelloWorldResponse WebATP.AisDataWebservice.AISDataretrieverSoap.HelloWorld(WebATP.AisDataWebservice.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebATP.AisDataWebservice.HelloWorldRequest inValue = new WebATP.AisDataWebservice.HelloWorldRequest();
            inValue.Body = new WebATP.AisDataWebservice.HelloWorldRequestBody();
            WebATP.AisDataWebservice.HelloWorldResponse retVal = ((WebATP.AisDataWebservice.AISDataretrieverSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebATP.AisDataWebservice.HelloWorldResponse> WebATP.AisDataWebservice.AISDataretrieverSoap.HelloWorldAsync(WebATP.AisDataWebservice.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebATP.AisDataWebservice.HelloWorldResponse> HelloWorldAsync() {
            WebATP.AisDataWebservice.HelloWorldRequest inValue = new WebATP.AisDataWebservice.HelloWorldRequest();
            inValue.Body = new WebATP.AisDataWebservice.HelloWorldRequestBody();
            return ((WebATP.AisDataWebservice.AISDataretrieverSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public void TransferAISPosition() {
            base.Channel.TransferAISPosition();
        }
        
        public System.Threading.Tasks.Task TransferAISPositionAsync() {
            return base.Channel.TransferAISPositionAsync();
        }
        
        public void TransferShipVoyageData(int MMSI) {
            base.Channel.TransferShipVoyageData(MMSI);
        }
        
        public System.Threading.Tasks.Task TransferShipVoyageDataAsync(int MMSI) {
            return base.Channel.TransferShipVoyageDataAsync(MMSI);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebATP.AisDataWebservice.TransferShipVoyageDataToServerResponse WebATP.AisDataWebservice.AISDataretrieverSoap.TransferShipVoyageDataToServer(WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequest request) {
            return base.Channel.TransferShipVoyageDataToServer(request);
        }
        
        public WebATP.AisDataWebservice.ShipVoyageData TransferShipVoyageDataToServer(int MMSI) {
            WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequest inValue = new WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequest();
            inValue.Body = new WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequestBody();
            inValue.Body.MMSI = MMSI;
            WebATP.AisDataWebservice.TransferShipVoyageDataToServerResponse retVal = ((WebATP.AisDataWebservice.AISDataretrieverSoap)(this)).TransferShipVoyageDataToServer(inValue);
            return retVal.Body.TransferShipVoyageDataToServerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebATP.AisDataWebservice.TransferShipVoyageDataToServerResponse> WebATP.AisDataWebservice.AISDataretrieverSoap.TransferShipVoyageDataToServerAsync(WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequest request) {
            return base.Channel.TransferShipVoyageDataToServerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebATP.AisDataWebservice.TransferShipVoyageDataToServerResponse> TransferShipVoyageDataToServerAsync(int MMSI) {
            WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequest inValue = new WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequest();
            inValue.Body = new WebATP.AisDataWebservice.TransferShipVoyageDataToServerRequestBody();
            inValue.Body.MMSI = MMSI;
            return ((WebATP.AisDataWebservice.AISDataretrieverSoap)(this)).TransferShipVoyageDataToServerAsync(inValue);
        }
        
        public void TransferShipHistory(int MMSI, System.DateTime startTime, System.DateTime endTime) {
            base.Channel.TransferShipHistory(MMSI, startTime, endTime);
        }
        
        public System.Threading.Tasks.Task TransferShipHistoryAsync(int MMSI, System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.TransferShipHistoryAsync(MMSI, startTime, endTime);
        }
    }
}
