//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ASTERIX_Cat62.WSGEO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSGEOSoap", Namespace="http://tempuri.org/")]
    public partial class WSGEO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WGS84TODATUM73OperationCompleted;
        
        private System.Threading.SendOrPostCallback DATUM73TOWGS84OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSGEO() {
            this.Url = "http://localhost/wsgeo/wsgeo.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WGS84TODATUM73CompletedEventHandler WGS84TODATUM73Completed;
        
        /// <remarks/>
        public event DATUM73TOWGS84CompletedEventHandler DATUM73TOWGS84Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WGS84TODATUM73", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StrctDATUM WGS84TODATUM73(StrctGEO WGS84) {
            object[] results = this.Invoke("WGS84TODATUM73", new object[] {
                        WGS84});
            return ((StrctDATUM)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWGS84TODATUM73(StrctGEO WGS84, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WGS84TODATUM73", new object[] {
                        WGS84}, callback, asyncState);
        }
        
        /// <remarks/>
        public StrctDATUM EndWGS84TODATUM73(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StrctDATUM)(results[0]));
        }
        
        /// <remarks/>
        public void WGS84TODATUM73Async(StrctGEO WGS84) {
            this.WGS84TODATUM73Async(WGS84, null);
        }
        
        /// <remarks/>
        public void WGS84TODATUM73Async(StrctGEO WGS84, object userState) {
            if ((this.WGS84TODATUM73OperationCompleted == null)) {
                this.WGS84TODATUM73OperationCompleted = new System.Threading.SendOrPostCallback(this.OnWGS84TODATUM73OperationCompleted);
            }
            this.InvokeAsync("WGS84TODATUM73", new object[] {
                        WGS84}, this.WGS84TODATUM73OperationCompleted, userState);
        }
        
        private void OnWGS84TODATUM73OperationCompleted(object arg) {
            if ((this.WGS84TODATUM73Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WGS84TODATUM73Completed(this, new WGS84TODATUM73CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DATUM73TOWGS84", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StrctGEO DATUM73TOWGS84(StrctDATUM D73) {
            object[] results = this.Invoke("DATUM73TOWGS84", new object[] {
                        D73});
            return ((StrctGEO)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDATUM73TOWGS84(StrctDATUM D73, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DATUM73TOWGS84", new object[] {
                        D73}, callback, asyncState);
        }
        
        /// <remarks/>
        public StrctGEO EndDATUM73TOWGS84(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StrctGEO)(results[0]));
        }
        
        /// <remarks/>
        public void DATUM73TOWGS84Async(StrctDATUM D73) {
            this.DATUM73TOWGS84Async(D73, null);
        }
        
        /// <remarks/>
        public void DATUM73TOWGS84Async(StrctDATUM D73, object userState) {
            if ((this.DATUM73TOWGS84OperationCompleted == null)) {
                this.DATUM73TOWGS84OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDATUM73TOWGS84OperationCompleted);
            }
            this.InvokeAsync("DATUM73TOWGS84", new object[] {
                        D73}, this.DATUM73TOWGS84OperationCompleted, userState);
        }
        
        private void OnDATUM73TOWGS84OperationCompleted(object arg) {
            if ((this.DATUM73TOWGS84Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DATUM73TOWGS84Completed(this, new DATUM73TOWGS84CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StrctGEO {
        
        private double latField;
        
        private double longField;
        
        private double heightField;
        
        /// <remarks/>
        public double Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        public double Long {
            get {
                return this.longField;
            }
            set {
                this.longField = value;
            }
        }
        
        /// <remarks/>
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StrctDATUM {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WGS84TODATUM73CompletedEventHandler(object sender, WGS84TODATUM73CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WGS84TODATUM73CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WGS84TODATUM73CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StrctDATUM Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StrctDATUM)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DATUM73TOWGS84CompletedEventHandler(object sender, DATUM73TOWGS84CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DATUM73TOWGS84CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DATUM73TOWGS84CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StrctGEO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StrctGEO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591