//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace TrackStatistics.WSGEO {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSGEOSoap", Namespace="http://tempuri.org/")]
    public class WSGEO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WSGEO() {
            this.Url = "http://localhost/wsgeo/wsgeo.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WGS84TODATUM73", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StrctDATUM WGS84TODATUM73(StrctGEO WGS84) {
            object[] results = this.Invoke("WGS84TODATUM73", new object[] {
                        WGS84});
            return ((StrctDATUM)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWGS84TODATUM73(StrctGEO WGS84, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WGS84TODATUM73", new object[] {
                        WGS84}, callback, asyncState);
        }
        
        /// <remarks/>
        public StrctDATUM EndWGS84TODATUM73(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StrctDATUM)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DATUM73TOWGS84", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StrctGEO DATUM73TOWGS84(StrctDATUM D73) {
            object[] results = this.Invoke("DATUM73TOWGS84", new object[] {
                        D73});
            return ((StrctGEO)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDATUM73TOWGS84(StrctDATUM D73, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DATUM73TOWGS84", new object[] {
                        D73}, callback, asyncState);
        }
        
        /// <remarks/>
        public StrctGEO EndDATUM73TOWGS84(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StrctGEO)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class StrctGEO {
        
        /// <remarks/>
        public System.Double Lat;
        
        /// <remarks/>
        public System.Double Long;
        
        /// <remarks/>
        public System.Double Height;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class StrctDATUM {
        
        /// <remarks/>
        public System.Double x;
        
        /// <remarks/>
        public System.Double y;
        
        /// <remarks/>
        public System.Double z;
    }
}
